--sql para database postgresql
CREATE DATABASE IF NOT EXISTS DEVBOOK;
USE DEVBOOK;

DROP TABLE USUARIO;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    NICK VARCHAR(255) UNIQUE NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE SEGUIDOR;

CREATE TABLE IF NOT EXISTS SEGUIDOR (
    USUARIO_ID int NOT NULL,
    SEGUIDOR_ID int NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (SEGUIDOR_ID) REFERENCES USUARIO(ID),
    PRIMARY KEY (USUARIO_ID, SEGUIDOR_ID)
);

DROP TABLE PUBLICACAO;

CREATE TABLE IF NOT EXISTS PUBLICACAO (
    ID SERIAL PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    CONTEUDO VARCHAR(255) NOT NULL,
    AUTOR_ID int NOT NULL,
    CURTIDA INT DEFAULT 0,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTOR_ID) REFERENCES USUARIO(ID)
);

